version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: banking-postgres
    environment:
      POSTGRES_DB: bank
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"